### ISSUE TITLE
A webtorrent browser add-on

### ISSUE THREAD

**Issue by 4t5tdgdertr** [feross/webtorrent#1017]
Would you guys consider making a browser add-on (webextension) for webtorrent? There are many reasons why this would be useful... For example I can just install the javascript once, and webtorrent will automatically work on any website that uses `src="torrent://<magnet-url>"`, users don't have to download the same library for every website that uses webtorrent, developers don't have to code anything they just have to use URLs in `src`, users might not have javascript enabled, reduce chances of people tampering with webtorrent javascript and incurring in XSS attacks, easier to update (just update the webextension instead of updating all the libraries in each website using it), no privacy issues with CDNs and trackings, less javascript, ....

**Comment by madovsky** [comment]
good idea, go ahead!!!

**Comment by goatandsheep** [comment]
The issue is that no webpages are going to use `src="torrent://<magnet-url>"` because not all browsers support WebRTC. Instead what I'm working on is a way to make it so web designers don't put an src at all. Instead they'd put an `href` and my [script (still figuring out the logistics of the project)](https://github.com/communotey/swarmpack) would:

1. Check WebRTC support
2. If no support, move the `href`s to the `src`s
3. If support, download the blob and make the blob the `src`

Also need to figure out how to cache blobs.

The size of WebTorrent is an issue that could be solved with a simple extension! I'll update you today

**Comment by feross** [comment]
I think a webtorrent browser extension is a cool idea. There's already an issue about it here: #443 If I get a free moment, I might hack it up, but anyone else is welcome to tackle it too.

The advantage of a chrome extension / chrome app is that it should be possible to support normal (tcp/utp) peers, meaning that users with this extension are more likely to find peers they can connect to, since they can connect to more than just the webrtc ones.
