### ISSUE TITLE
Can not download file in Transmission client

### ISSUE THREAD

**Issue by BOOMER74** [feross/webtorrent#1025]
Hi! I try to download torrent from Transmission client, but all attempts fails. I use both `webtorrent` and `webtorrent-hybrid` modules on `node` and `electron`, but Transmission still not found peers. For example, this is simple script:
```js
(new require("webtorrent")()).seed("some-file", (torrent) => {
    torrent.on('warning', (err) => console.log(err));
    torrent.on('error', (err) => console.log(err));

    console.log(torrent.magnetURI);
});
```
WebTorrent Desktop download file if i use `webtorrent-hybrid` on `node` or `webtorrent` on `electron`, but Transmission not working in any case. But if download first in WebTorrent Desktop and then add in Transmission, all works (that means this is not network trouble).

What i do wrong? I need upload file to a server (where used Transmission) in `electron` or `nw.js` app.

**Comment by feross** [comment]
Using torrents to upload files to your server doesn't seem like the most reliable tool for the job, to be honest. Torrents aren't ideal for 1-to-1 communication. They excellent when there are lots of people who want or have the same file.

That said, I think this issue is caused by you not waiting long enough before initiating the download from Transmission, since it takes some time to announce the torrent to the DHT. Try waiting for the `dhtAnnounce` event before adding the magnet url to Transmission.

You can also improve the reliability if you specify some working tracker servers as the `announce` option to `client.seed()`:

```js
client.seed('some-file', { announce: [ 'tracker_url', 'tracker_url2' ] }, callback)
```
