### ISSUE TITLE
ffmpeg stream all formats video

### ISSUE THREAD

**Issue by gabrielpf** [feross/webtorrent#1041]
Hi, 
It's possible to use [https://github.com/damianociarla/node-ffmpeg](https://github.com/damianociarla/node-ffmpeg) for stream all video formats ?

**Comment by kocoten1992** [comment]
To browser ? I don't think it possible ALL format yet

x264: all major browser support x264
VP9: safari not support it yet
x265: no browser support it yet

**Comment by feross** [comment]
@gabrielpf Thanks for the link to that module. This functionality doesn't belong in webtorrent. In the browser it wouldn't work, since that's a native module. In webtorrent-cli, your video player (like VLC) will support many or all possible formats. In WebTorrent Desktop, we already have issues discussing how to increase codec support.
