### ISSUE TITLE
Every torrent opens 3 new websockets for tracking

### ISSUE THREAD

**Issue by 6f7262** [feross/webtorrent#1062]
**What version of WebTorrent?**
0.98.8

**What operating system and Node.js version?**
Windows 10 & Mac OSX Sierra

**What browser and version? (if using WebTorrent in the browser)**
Chrome Version 56.0.2924.87 (64-bit)

**What did you expect to happen?**
Not opening 3 websockets for tracking per torrent.

**What actually happened?**
Every torrent you add, 3 websockets are opened for tracking. When adding many torrents at a time this causes browsers to crash. Even adding 3-4 torrents makes it almost unusable. Surely it makes more sense to open 3 trackers and send 300 messages than open 300 trackers and send 300 messages.

**Comment by DiegoRBaquero** [comment]
@feross Seems the pool broke! This is urgent. Will investigate.

**Comment by DiegoRBaquero** [comment]
This is the commit that should be reverted: https://github.com/feross/bittorrent-tracker/commit/3f3db7deb1f7b1e1a6364990ba4fcfc2d4bd6130

Sockets are no longer closed on eviction.

Need to fix that in uwt too.

**Comment by feross** [comment]
@DiegoRBaquero Right you are! Sorry, this is my bad! PR incoming.

**Comment by feross** [comment]
Just committed to `master` and released bittorrent-tracker@8.5.2 since this is a bad bug.

**Comment by feross** [comment]
https://github.com/feross/bittorrent-tracker/commit/1dd1cc32da58bcb6c23cc30c6fdc8d0348f9656f

**Comment by DiegoRBaquero** [comment]
@feross can we get a new webtorrent build?

We should automate builds on modules update (at least modules built specifically for webtorrent such as the tracker(?))

**Comment by feross** [comment]
@DiegoRBaquero Done. Published as 0.98.10. @DiegoRBaquero I also gave you npm publish rights so that you can help with this process in the future.

You can do a build with `npm run build`. However, it's easy to forget to do all the steps when publishing a new release, so I recommend setting up terminal aliases for publishing new versions. My aliases are listed here: https://github.com/feross/prezto/blob/master/runcoms/zshrc#L30-L34 

You can run `patch`, `minor`, or `major` to do a release of the given type and it will take care of all the steps. Note: If there is a build or the authors file is updated, then it won't proceed all the way to publish. It will stall and wait for you to `git commit` the changed file. To continue the process, run `postversion`. Don't re-run `patch`, `minor`, or `major` a second time, or you will increment the version a second time!

Let me know if you have any questions or run into problems.
