### ISSUE TITLE
In theory: webtorrent and tor

### ISSUE THREAD

**Issue by fsteff** [feross/webtorrent#1066]
I recently read this article: [https://blog.torproject.org/blog/bittorrent-over-tor-isnt-good-idea](url) and I asked myself if this also applies to webtorrent.

In short: Bittorrent and tor are a bad combination because a) the tracker needs (and distributes) your real IP and b) the bittorrent protocol uses UDP, which is not supported by tor.
(I am not talking about the tor browser bundle, which does not support WebRTC and blocks javascript per default - rather using tor as a proxy in general)

I am no expert with WebRTC so I´m asking you if these arguments also apply to webtorrent.
Privacy is a major problem, especially when a website uses it to distribute the server load - everybody can see who is visiting the website.  This actually is a reason for me not to use it at all in websites.
(similar: https://github.com/feross/webtorrent/issues/788)

**Comment by feross** [comment]
WebRTC can connect over UDP or TCP, so I believe that TCP would be used if all your traffic was being tunneled over a Tor proxy.

But I'm not actually whether STUN would be supported over Tor. I thought they used UDP, but apparently they can also be sent over TCP. Unsure if browsers support that, but it's worth investigating further.

If *all* your traffic is set up to go through the Tor proxy then I believe you're safe, since you're never talking directly to the internet. But if STUN packets require UDP in current browsers, then I bet that WebRTC connections wouldn't work at all.

Only one way to find out!
