### ISSUE TITLE
Information Seedbox

### ISSUE THREAD

**Issue by Smallkan** [feross/webtorrent#1085]
Is it possible to use a seedbox to seed the torrent for instant.io?

**Comment by kocoten1992** [comment]
check out issue 214 and 1079, closet thing is use webseed (but webseed require at least one peer connected - I think that a bug)

I can't config vuze to seed up, can only download
webtorrent-hybrid not working right

**Comment by Smallkan** [comment]
Who could do a setup to use a simple seedbox.

**Comment by DiegoRBaquero** [comment]
Webseeds are the way to go.

**Comment by kocoten1992** [comment]
Hey @DiegoRBaquero , you edit my comment wrong issue, wasn't want to direct to it the first place, but anw, it 319 not 214

319 because I though it would be possible to install LXQT and use browser as a seed box, but no, it all handle in ram.

I would love to have a torrent client that expand on multiple machine and do rebalance seed when add more machine to it, hmm

**Comment by DiegoRBaquero** [comment]
Couldn't really understand you. I just added linked the issues.

Do "rebalance" a webseed you can use a CDN. To "rebalance" wrtc seeding, you can simply seed from more machines.

**Comment by kocoten1992** [comment]
I just edit it back but nvm, I might typo it first :smiley: 

Don't remember it clear, it seem that current webtorrent webseed always download regardless of getting from peer - always from the server (and do mind if asked to test again), only one thing that work really well are peer to peer right now.
