### ISSUE TITLE
File smaller than 100MB doesn't autoplay/stream

### ISSUE THREAD

**Issue by staltz** [feross/webtorrent#1098]
**What version of WebTorrent?**

Whatever version is running in Instant.io. But I first experienced this with webtorrent-hybrid seeding the file.

**What operating system and Node.js version?**

macOS Sierra 10.12.4, in the browser

**What browser and version? (if using WebTorrent in the browser)**

Google Chrome 57.0.2987.133

**What did you expect to happen?**

Seed a file from instant.io smaller than 100MB. For instance this one https://instant.io/#f9ab2edf3187fe62758f20603179ab90007d211e is 91MB (90788515 bytes). Expect to see that video autoplay when opened from another tab.

**What actually happened?**

Does not autoplay while streaming. It waits until it downloads 100%, then plays.

- - -

I suspect this happens due to some export config of my MP4, but not sure what are the settings that  WebTorrent appreciates.

**Comment by DiegoRBaquero** [comment]
Does it auto play when it has finished downloading it?

**Comment by feross** [comment]
I don't think the file size is relevant. In order to stream MP4s, they must be fragmented and the `videostream` package must support streaming them. So if you're having an issue, I suspect it's due to the MP4 not being fragmented, or a bug/missing feature in `videostream`.

If you already have an MP4, but it's not properly fragmented, you can again use ffmpeg:

```
ffmpeg -i non_fragmented.mp4 -movflags frag_keyframe+empty_moov fragmented.mp4
```

More info: https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API/Transcoding_assets_for_MSE

Also, @jhiesey might have more thoughts on how best to export your files.

**Comment by F-loat** [comment]
Hi, I have some doubts with this param`frag_keyframe+empty_moov`, I know this param will generate a file that fragmented but the fragmented file only play when it has finished downloading.
```
ffmpeg -i non_fragmented.mp4 -movflags frag_keyframe+empty_moov fragmented.mp4
```
And this below work fine.
```
ffmpeg -i non_fragmented.mp4 -movflags faststart fragmented.mp4
```
Should I do something extra with fragmented.mp4?
