### ISSUE TITLE
Webtorrent scaling, streaming

### ISSUE THREAD

**Issue by klonodo** [feross/webtorrent#145]
1. It would be nice to have a tool to make .mp4 meta file readable by webtorrent and functionality in webtorrent that would check in the list of files in current torrent file, if file named for example 'meta.info' exist, if true then seeking could be enabled.

2. When streaming into <video> tag will be implemented into browser webtorrent client? Could you provide some ETA please? 

3. From what i see webtorrent is using websocket tracker. On daily basis i have around 200k peers. Normally if i set interval of announce at minimum 15 minutes then i have around ~222 announces per second, so i have 222 connections a second, so i only need resources for around 200-300 connections at any time for tracker. Current design of webtorrent make me need resources for 200 000 connections via websockets. 
You wrote that " * This is necessary to facilitate the WebRTC signaling (peer introduction) process."
Can we offload peer introduction to clients making ajax calls instead of using websockets?

**Comment by feross** [comment]
Video streaming arbitrary MP4s into the `<video>` tag is now possible, using the [videostream](https://www.npmjs.com/package/videostream) module by @jhiesey. This module repackages the MP4 or M4A on-the-fly in JS so that it can be played back by the MediaSource API in the `<video>` or `<audio>` tag. videostream is build on top of a forked version of mp4box.js.

videostream isn't built into WebTorrent directly yet, so you can't just use the `file.createReadStream().pipe(video)` API. You can see an example of how to use it [here](https://github.com/feross/instant.io/blob/4513e0eb98ab31a2e8ae969bb0708cce5dbaff54/client/index.js#L155-L241), and it's running live on https://instant.io right now!

@klonodo's original issue is now resolved, so I'm closing this.
