### ISSUE TITLE
downloader fails to find seeder

### ISSUE THREAD

**Issue by mvayngrib** [feross/webtorrent#194]
Hi Feross,

I'm new at WebTorrent, so this may be a stupid question. I wrote this simple test to see if a seeder and a downloader connect. They don't, which leads me to think I'm using the library incorrectly. Can you give me a hint? 

    var test = require('tape');
    var WebTorrent = require('webtorrent');

    test('seed torrent with one client, download with another', function(t) {
      var client1 = new WebTorrent();
      var client2 = new WebTorrent();

      var buf = new Buffer('short novel about blah');

      client1.seed(buf, { name: 'blah' }, function(torrent1) {
        var timeoutId = setTimeout(function() { 
          t.fail();
          t.end(); 
        }, 30000);

        client2.download(torrent1.infoHash, function(torrent2) {
          // never gets here
          clearTimeout(timeoutId);
          t.equal(torrent1.infoHash, torrent2.infoHash);
          t.end();
        });      
      });
    });

**Comment by feross** [comment]
Hey @mvayngrib, sorry for not replying sooner. This is a really simple issue.

This line is the culprit:

```js
    client2.download(torrent1.infoHash, function(torrent2) {
```

In general, you don't want to download with just an infoHash because then you have to rely *only* on the DHT, which is slower than using trackers. Also, announcing to the DHT takes some time, and you're trying to search it before the message has even gotten out.

You could make your example work by switching to using `torrent1.magnetURI` instead of `torrent1.infoHash`.

Or, instead you can wait for the `torrent.on('dhtAnnounce')` event to know that announcing has succeeded before you start with `client2`.

**Comment by mvayngrib** [comment]
ah, i see, thanks

**Comment by cubuspl42** [comment]
@feross Did you test your solution? It does not work for me.
https://gist.github.com/anonymous/3cb860cddc6a4651e59001bd6b434d59
