### ISSUE TITLE
A few questions regarding using webtorrent for 1-to-1 private file sharing

### ISSUE THREAD

**Issue by szimek** [feross/webtorrent#263]
1. Does creating magnet uri require reading the whole file on the seed/sender side? Is there a way to get some progress notifications when processing larger files (e.g. +1GB)?
2. What does webtorrent use on the recipient side to store files? filesystem api, indexeddb? 
3. What options do I need to set, so that others won't be able to download a file that I want to send only to a specific recipient? 
4. Does webtorrent automatically handle connection failures, e.g. when computer goes to sleep and then wakes up etc.?
5. How can I get transfer progress notifications on sender and recipient side?

I'm thinking about using webtorrent in https://www.sharedrop.io instead of my current crappy and slow (but working) code for handling file transfers.

**Comment by DiegoRBaquero** [comment]
@szimek 
1. Yes, at the moment it is required. The notification is the onTorrent event, when metadata is ready.
2. FS for node, nothing for browser atm. You can check https://github.com/DiegoRBaquero/ls-chunk-store, but it's limited to around 1.5MB.
3. Set the announce list to your trackers only or empty and use the {private: true} opt.
4. No idea
5. torrent.on('download') and torrent.on('upload')

Trying to close issues, if you feel this can be closed, please let us know.

**Comment by szimek** [comment]
@DiegoRBaquero Thanks!

**Comment by feross** [comment]
@szimek I'll add the following to @DiegoRBaquero's answers:

1. We should add some progress events since for 1GB+ files, there's no feedback while the hashes are calculated.
3. The safest thing to do is to encrypt the file on the client-side and include the decryption key in the link. Otherwise, there's not much you can do to prevent the tracker server from telling someone the infohash so it can be downloaded.
4. Connection interruptions, like from laptop sleep, are automatically handled!

Let me know if you have other questions. I'm happy to help.
