### ISSUE TITLE
Unverified pieces get stuck until all pieces finish downloading

### ISSUE THREAD

**Issue by adammw** [feross/webtorrent#266]
e.g. piece 59 in the screenshot below

![screen shot 2015-02-16 at 12 28 03 am](https://cloud.githubusercontent.com/assets/153219/6203374/c7432706-b572-11e4-87fa-2819f04129a5.png)

**Comment by yipperr** [comment]
shady need to obfuscate the image

**Comment by grunjol** [comment]
I think you are seeing that because the green represent non-BLOCK_BLANK blocks, which includes reserved blocks.

on cmd.js [line 461] (https://github.com/feross/webtorrent/blob/master/bin/cmd.js#L461) you can replace 
```
bar += piece.blocks[j] ? '{green:█}' : '{red:█}'
```
with 
```
bar += piece.blocks[j] ? (piece.blocks[j] === 1 ? '{blue:█}' : '{green:█}') : '{red:█}'
```
and you will see reserved blocks in blue.



But not all reserved blocks will be shown, because if you have reserved blocks on pieces without any written block, the condition on [line 456] (https://github.com/feross/webtorrent/blob/master/bin/cmd.js#L456) will skip it
```
if (piece.verified || piece.blocksWritten === 0) {
    continue
}
```
so, something like this can be used to skip the condition

```
if (piece.verified || !piece.blocks[0]) {
    continue
}
```
even if it doesn't check all the blocks, as far i can see when starting with a new piece it starts with the first block, so its a kind of better approach

**Comment by adammw** [comment]
I'm not sure exactly what "reserved" means in this context, but yeah with that change I'm seeing that the pieces that get stuck do have 'blue' segments in them, I was really unfortunate with this one as it happened on the first block so I had to wait for the entire file to be downloaded before it would go back and try again.
![screen shot 2015-02-18 at 9 37 29 pm](https://cloud.githubusercontent.com/assets/153219/6245814/8886f1e6-b7b6-11e4-8906-b58c3eb98de7.png)

**Comment by feross** [comment]
@grunjol's fix in https://github.com/feross/webtorrent/pull/272 should resolve this issue! Please give webtorrent@0.27.2 a try, and please let us know if this does the trick.
