### ISSUE TITLE
Bridges

### ISSUE THREAD

**Issue by fbodz** [feross/webtorrent#274]
How are the bittorrent to webtorrent bridges going to work ?
Cheers.

**Comment by Svenskunganka** [comment]
By getting people to use hybrid clients (which I believe Feross is working on) or getting the larger clients (uTorrent, Transmission, etc) to add WebRTC support.

Watch Feross JSConf talk [here](https://www.youtube.com/watch?v=kxHRATfvnlw) and you'll understand, he's explaining it **really** good.

**Comment by fbodz** [comment]
Is there any active development on the hybrid nodes?

**Comment by fbodz** [comment]
@feross When will you be releasing the support for hybrid clients

**Comment by feross** [comment]
There's a module called wrtc (https://www.npmjs.com/package/wrtc) which provides bindings to the Google WebRTC C++ libraries in node, so that's always an option. There's a bit of refactoring work that needs to happen to enable this first. No code is released on GitHub yet, but I've started working on this locally.
