### ISSUE TITLE
Downloading doesn't start

### ISSUE THREAD

**Issue by xylosper** [feross/webtorrent#310]
Thank you for great work, but I couldn't get successful result yet.

I'm trying to test streaming with next commend:
```
$ webtorrent <torrent file> -i 0 --mpv
```
But the downloading wouldn't start.
I've waited for 4 minutes for `webtorrent`.

For comparison, with same command for `peerflix`,
```
$ peerflix  <torrent file> -i 0 --mpv
```
downloading started in about 30secs and streaming started in about 1min.

Is this limited by WebRTC which webtorrent using? Or, can I try something more?

**Comment by feross** [comment]
I've noticed recently where the webtorrent node client aggressively disconnects from peers, leaving very few or none left to download from. This is a bug.

**Comment by grunjol** [comment]
I noticed the same thing.I tested back all the versions and found it started with release 0.32.
0.31 is working fine.

**Comment by DurandA** [comment]
I am experiencing the same issue with both 0.39 and 0.40.

**Comment by DurandA** [comment]
I believe the issue comes from the upgrade to bittorrent-swarm@2 with WebRTC support. This is the only major modification between 0.31 and 0.32. https://github.com/feross/bittorrent-swarm/commit/1af8d8ff19a824f195b6886569f3d82148e3f37a

**Comment by feross** [comment]
@grunjol @DurandA You're right. Just confirmed that the issue started with webtorrent 0.32.

If you just use webtorrent for normal torrenting, I suggest using webtorrent 0.31 until this issue is fixed.

**Comment by ericwooley** [comment]
Anything new on this? I am a bit stuck, I am trying to use the webtorrent in a node program, and I get no connections, I also git no connections using the webtorrent cli. Any bandaids or anything? I don't want to downgrade to .31 because that seems to introduce several other bugs

**Comment by feross** [comment]
### EXCELLENT NEWS EVERYONE!

#### This bug is fixed in webtorrent v0.53.0 – wohoo!

About time! This was the longest I've ever spent trying to track down a bug -- several days, I lost count. And I still don't quite understand what's going on. The piece selection code needs a good refactor to get to the bottom of this. But the regression is fixed!

Now if you give `webtorrent` or `webtorrent-hybrid` a try, it'll connect **and stay connected** to normal bittorrent peers.

#### Here's what you should try now:

Install `webtorrent-hybrid`:

```
npm install webtorrent-hybrid -g
```

Pick a video torrent you want to stream:

```
webtorrent-hybrid some.torrent --vlc
```

The video will start playing in VLC.

Now, go to https://instant.io. Drag-and-drop the .torrent file onto the page.

It should start playing **before the complete file is downloaded in `webtorrent-hybrid`**. In other words, `webtorrent-hybrid` seeds to web peers while it's still a downloader, like you'd expect a good torrent client to do.

We're getting closer to the final vision of WebTorrent – get excited!

**Comment by solderzzc** [comment]
Excellent update. I started using webtorrent instead of peerflix three days
ago. And the issue fixed so quick that I can continue to use it in my
project.

Really appreciate for your amazing work.

**Comment by feross** [comment]
No problem - thanks!
