### ISSUE TITLE
webtorrent CLI errors when a torrent does not end with a newline

### ISSUE THREAD

**Issue by line-o** [feross/webtorrent#328]
when running 

    ▷webtorrent seed http://bitlove.org/jupiterbroadcasting/bsdnowhd/bsd-0001.m4v.torrent

you get 

    ERROR: ENOENT, scandir 'http://bitlove.org/jupiterbroadcasting/bsdnowhd/bsd-0001.m4v.torrent'

Manually adding a newline to the end of the torrent file fixes this.

**Comment by feross** [comment]
Try updating the latest webtorrent (I just pushed a fix), and use this command:

```
webtorrent download http://bitlove.org/jupiterbroadcasting/bsdnowhd/bsd-0001.m4v.torrent
```

`webtorrent seed` is meant for creating a new torrent, so it takes a path to a file or folder of content, not a .torrent file. We should improve the docs, or maybe detect when a .torrent file or magnet link is used and just do the right thing, since this issue has come up before.

**Comment by line-o** [comment]
OK, works fine

**Comment by feross** [comment]
Alright, I just made the `webtorrent seed` command smarter. It'll change `webtorrent seed` to `webtorrent download` if you pass in a .torrent file or magnet uri. Hopefully this isn't a bad idea :-)
