### ISSUE TITLE
Shasum check failed for multiparty

### ISSUE THREAD

**Issue by markpatx** [feross/webtorrent#364]
I am trying to install webtorrent on a linux vm and I am getting this error:

npm ERR! Linux 2.6.38
npm ERR! argv "/root/.nvm/versions/node/v0.12.5/bin/node" "/root/.nvm/versions/node/v0.12.5/bin/npm" "install" "-g" "webtorrent"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2

npm ERR! shasum check failed for /tmp/npm-6998-6f2e14eb/registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
npm ERR! Expected: a567c2af000ad22dc8f2a653d91978ae1f5316f4
npm ERR! Actual:   aa59b8a177dfc2c64275675f9dbf40fbe7d65632
npm ERR! From:     https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz

I tried the command "npm install multiparty" and seems to work fine, but I still get the error when trying to install webtorrent.

How could I fix it?

**Comment by markpatx** [comment]
Tried on another linux and it worked fine. But when I try to run the examples, I browserify the .js and load it on the browser with something like:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>test</title>
    <script src="app.js"></script>
</head>
<body id="home">
</body>
</html>

But nothing happens, no errors on console or anything, just a blank page.

**Comment by feross** [comment]
The first error looks like a busted npm cache. Next time you see that, try running `npm cache clean && sudo npm cache clean && rm -rf node_modules/`, then try the install again.

Regarding your second comment, you're probably seeing a blank page because there are no seeders for the torrent you're testing with (the one in the readme). The torrent needs to be seeded by a webrtc-capable client, i.e. [webtorrent-hybrid](https://github.com/feross/webtorrent-hybrid) or [instant.io](https://instant.io/). Try going to [instant.io](https://instant.io/) and seeding any file, then use that infohash in your sample code.
