### ISSUE TITLE
Best solution for private torrents?

### ISSUE THREAD

**Issue by Canifex** [feross/webtorrent#386]
What would be the best solution to set up private file transfer, so if I want to share a file only with some people or just one person. Would a private tracker be the way to go? 

As far as I understood the api, the whole sending / receiving process is inteded to work "cross domain" with all seeders and leechers. Is there any way to create private torrents or to implement an own authentication process to only allow specific persons to download a file I am seeding?

**Comment by feross** [comment]
You should consider encrypting the file and only sharing the key with the person who you want to receive the file. That way, if the hash of the file leaks out somehow -- say via a bug in webtorrent https://github.com/feross/webtorrent/issues/271 -- the file will be worthless.

Running your own private instance of [`bittorrent-tracker`](https://github.com/feross/bittorrent-tracker) and explicitly disabling the DHT with the `{ dht: false }` option to the `WebTorrent` constructor would help too.

When you create .torrent files with [`create-torrent`](https://github.com/feross/create-torrent) or by calling `webtorrent.seed`, make sure to use the `{ private: true }` option to tell clients to not share the hash with the DHT or with other peers using peer exchange (PEX).

Feel free to share your findings here, so that others who are trying to do the same thing can benefit!

**Comment by Canifex** [comment]
Is there any option to do this on client side? So, is there any hook/callback available if someone downloads a file / part of a file from me? That way, I could restrict access to files on client side by forbidding the download.

**Comment by DiegoRBaquero** [comment]
@Canifex Yes, let me explain further what feross said.

You must do `var client = new WebTorrent({ dht: false })` and when seeding the private feel do `client.seed(myFile, {private: true})`

I hope this helps :)

**Comment by Canifex** [comment]
@DiegoRBaquero thanks for your fast helper (and of course @feross for the help before). 

I understood that I can use a private tracker and seed files privatly with these options. But is there any additional option on client side to hook in if someone requests one of my seeded files? This would make it possible to implement some security logic on the client, not on a centralized tracker, which could be untrustable from a client's perspective.

For example sth like:

```js

var client = new WebTorrent({ dht: false });
client.seed(myFile, {private: true})
client.onLeech(function(file, leecher){
  if (downloadAllowed(file, leecher)) {
    return true;
  } else {
    return false;
  }
});

```

**Comment by DiegoRBaquero** [comment]
No, at the moment there is not, and I doubt there will be (I think). 

As long as you use those options and use a private tracker and don't share the hash/magnet/.torrent with unauthorized people, there's no way to find the file.

**Comment by feross** [comment]
There is actually a way to inspect the handshake that the remote peer sends you, and maybe even intercept it / decide to reject it.

The `bittorrent-protocol` package supports an [extension API](https://github.com/feross/bittorrent-protocol/blob/master/README.md#extension-api). Here's an example of an extension implemented with it: https://github.com/feross/ut_metadata/blob/master/index.js

If you hook into the `'wire'` event on the torrent, you can add support for your special client-side handling.

Here's some untested code for how you might do it:

```js
torrent.on('wire', function (wire) {
  wire.use(myExtension())
})
```

Beware that this is really, really low-level.
