### ISSUE TITLE
Question on webrtc peers vs regular tcp/udp peers

### ISSUE THREAD

**Issue by joshuaterrill** [feross/webtorrent#406]
I was looking at the webtorrent-hybrid repo and saw that, "webtorrent no longer connects to WebRTC peers, just normal TCP/UDP peers." If this is the case, why do magnets/torrents still have to be seeded by a webtorrent system like instant.io?

**Comment by feross** [comment]
Sorry for the confusion. That statement means that the `webtorrent` package doesn't try to connect to WebRTC peers anymore - you need to use `webtorrent-hybrid` if you want to do that. In other words, the feature was removed from the `webtorrent` package since it was too hard to compile the dependencies.
