### ISSUE TITLE
Too many rtc peer connections with no reason

### ISSUE THREAD

**Issue by vkefallinos** [feross/webtorrent#415]
I just loaded(seed) a file in instant.io and it starts opening dozens of rtcpeerconnections without even starting to download.
![toomanyrtc](https://cloud.githubusercontent.com/assets/1502852/9590787/85e963a2-503f-11e5-872b-0be6fa9cd93b.png)

Is this normal?

**Comment by eliooses** [comment]
When no seeds found, automatically the script starting switch ports to connect and find someone peers.

I pressume what that is your issue.

**Comment by feross** [comment]
@vkefallinos All these peer connections are opened so that the WebRTC "offers" that your browser generates can be sent to the tracker server and be used by potential peers. Each peer connection has a timer that ensures that the peer connection objects are destroyed when no one connects to them for ~60 seconds. This is not a cause for concern. WebTorrent is working as expected.
