### ISSUE TITLE
Proxy!

### ISSUE THREAD

**Issue by anweshknayak** [feross/webtorrent#419]
How to bypass proxy ? Is there any specific command ?
What to do if UDP is blocked ? Although we can add trackers in torrent Client.

**Comment by RaulTsc** [comment]
Anything?

**Comment by anweshknayak** [comment]
I wish.

**Comment by gadido30** [comment]
SpooferBT:
https://github.com/mcourteaux/SpooferBT

**Comment by feross** [comment]
If your network is blocking UDP traffic, then you're out-of-luck getting webtorrent in node to work today.

Later, when there are lots of WebRTC peers (and we get WebRTC support included the default `webtorrent` package instead of `webtorrent-hybrid`), you'll probably be better off. WebRTC automatically does NAT hole punching, so it ought to work even with a pretty restrictive router.
