### ISSUE TITLE
Extreme memory consumption when restarting torrent

### ISSUE THREAD

**Issue by ngjermundshaug** [feross/webtorrent#441]
Hi

First off - awesome library! Love it!

One challenge though. But when I stop and restart the download of a torrent - the memory consumption goes haywire. I've tested this with a torrent with 2172 files - total size is 9GB - 1MB piece size.

![Mem](http://content.screencast.com/users/njalgjermundshaug81/folders/Jing/media/2bd85bde-97a6-4b04-9f20-1fec45d1aebe/2015-09-24_1511.png)

It loads a whopping 9GB into memory. I'm guessing this is related to rechecking all the pieces. I'm running this is NW.JS - so the UI freezes when this being done. After about 10 secs - the memory consumption returns to normal - and the UI is responsive again.

Same thing happens when I restart the program and resume the download of a torrent that is not finished - which has to be rechecked.

How should I get around this issue?
Can you make rechecking pieces/hashing more memory friendly?

**Comment by feross** [comment]
@ngjermundshaug Thanks for the kind words, sorry for not replying sooner.

This issue was fixed on Jan 9, 2016 in https://github.com/feross/webtorrent/commit/664eb30006216dfd6c6a62c78c74c16f3e5f8809.

Before, we'd try hashing every piece in the torrent in parallel, which is usually ~1000 pieces per torrent. Now, it's limited to the number of cores on the machine.

Please let me know if this improves the situation!
