### ISSUE TITLE
HTTP Live Streaming for Webtorrent

### ISSUE THREAD

**Issue by datnguyencse** [feross/webtorrent#448]
Please think about it, a player use p2p (webtorrent) and HLS (m3u8) or video ( mp4, flv....) would be interesting. I am looking  for this but not found any player free, https://www.peer5.com/ or http://www.streamroot.io/ is two of the best but trial only, not free.

**Comment by rom1504** [comment]
That's an interesting topic yeah. It's probably out of scope for webtorrent, but you might want to look into that recent work from substack https://github.com/substack/append-only-torrent

**Comment by ericwooley** [comment]
I am working on a project to do this (webm only for now). You need to mess with the init headers of the video, and make sure codecs line up. If you want to look through how it works so far. If there is interest in helping with my project, I plan to open source it eventually. I can open source it sooner rather than later. I just want to clean it up and make a clear roadmap first.

https://github.com/ericwooley/VideoAppendTesting/blob/master/src/scripts/libs/media-streamer.js

https://github.com/ericwooley/VideoAppendTesting

http://ericwooley.github.io/VideoAppendTesting/

**Comment by brusacco** [comment]
Any updates about this?
Found https://github.com/bemtv/bemtv ...

There are any samples of seeding from a buffer? Maybe we can load the remote mp4 into a buffer, and seed it? Or must be the hole file in buffer. Thanks!

**Comment by jimmywarting** [comment]
Just want to point out that HLS is not a standard and it would be nice to lean towards DASH api instead

[what is the difference between hls and mpeg dash](http://stackoverflow.com/questions/15687434/what-is-the-difference-between-hls-and-mpeg-dash)
[browser support](https://developer.mozilla.org/en-US/Apps/Build/Audio_and_video_delivery/Live_streaming_web_audio_and_video#Streaming_File_Format_Support)

At the very best: build DASH support with HLS fallback. if HTTP Live Streaming for Webtorrent ever becomes a thing

**Comment by Cheedoong** [comment]
Agree with @jimmywarting   Recall the history of .avi, .flv, ..., and the ISO standard .mp4; Gopher and the W3C/IETF standard HTTP...

**Comment by feross** [comment]
Looks like there's some cool experimentation going on here :+1: Feel free to continue discussing, but I'm going to close this issue since it's out-of-scope for this repo (and the main webtorrent project). This makes it easier to see where the real issues are :)
