### ISSUE TITLE
pure browser based popcorn time alternative 

### ISSUE THREAD

**Issue by kof** [feross/webtorrent#464]
Do you think its hard to do? What are the issues we would have to solve?

**Comment by gauravsaini** [comment]
I think people are already trying it before as well . There is a popcorn time build based on webtorrent.js 
But it is not allowed to discuss this over here.

**Comment by kof** [comment]
any links?

**Comment by ericwooley** [comment]
The real issue you are getting at is sharing data between the non-webrtc torrent network and the webrtc (webtorrent) clients. You need some kind of bridge, which is what webtorrent hybrid is about.

**Comment by kof** [comment]
Right, they are using different data protocols ...

**Comment by kof** [comment]
We should actually make popcorntime  use webtorrent in parallel to allow both. Maybe someone has connections to those guys? They have closed forum, not every one can write there.

**Comment by ericwooley** [comment]
I would probably stop talking about popcorn time specifically here, I doubt webtorrent wants to be associated with pirating.

The other thing to think about is how webtorrent users will rarely be good seeders, they will leach for a while and bail. You would need to convince services that there is a benefit to a browser version, because it will drain their other users.

It might be a good idea for some kind of browser extension that provides a global version of webtorrent, which individual pages should check for before creating their own client, so that the instance can span pages and be a better citizen for seeding. If this were to pick up, pages that use webtorrent can advertise the extensions which would offer better persistance etc...

**Comment by kof** [comment]
> webtorrent users will rarely be good seeders

why?

**Comment by feross** [comment]
Don't use WebTorrent for copyright infringement. The WebTorrent project and contributors don't support piracy and cannot help with your questions. See our [rules](https://github.com/feross/webtorrent/blob/master/CONTRIBUTING.md#webtorrent-contributing-guidelines) for information.

This discussion is closed and locked.
