### ISSUE TITLE
Why KAT torrents dont download on the browers

### ISSUE THREAD

**Issue by MurWade** [feross/webtorrent#466]
Hi, noob here

When i get a magnet link from kickass torrents they download fine with [jstorrent](https://github.com/kzahel/jstorrent) which is a chrome extension but the links fail to download using webtorrent on the browser. it is not possible to download any magnet links from kickass torrent on [instant.io](https://instant.io/). instant.io uses webtorrent Is this suppose to not work in the browser or what.  sorry not very familier with p2p.

**Comment by TomasHubelbauer** [comment]
*WebTorrent* can only download torrent that other *WebTorrent* peers seed. Torrents from KAT are not seeded by any other peers from [instant.io](http://instant.io) and thus cannot be downloaded through *WebTorrent*. I believe @feross is researching bridging desktop torrent clients and *WebTorrent* so they can interoperate, which can be achieved by the desktop clients supporting WebRTC.

**Comment by MurWade** [comment]
ok i see. 
thank you for the explanation. 

so if a user seeds a file it will only be downloadable to peers that use webtorrent also? the other peer would need the magnet link that is all?

**Comment by TomasHubelbauer** [comment]
Yep, when you go to [instant.io](http://instant.io) and upload a file, copy the info hash, open a new tab and download a file using that info hash, you will be able to get that file, and so should any other peer using *WebTorrent*.

**Comment by MurWade** [comment]
Thanks again man. 

Is it possible to get list of all torrents currently available on webtorrent?

**Comment by TomasHubelbauer** [comment]
I don't know. I don't think *BitTorrent* protocol itself includes any content discovery mechanisms, that's why BitTorrent trackers exist. The bridging solution I was talking about earlier I presume would work by implementing a tracker server software which supports both desktop torrent clients and *WebTorrent* and serves the pieces between both kinds of clients transparently. Tracker servers are not standardizes AFAIK and thus each one has different content discovery mechanisms, in case of KAT and most of the others, this purpose is served by the website that lists the torrents in the tracker's database. Theoretically you can enumerate KAT's torrents by scraping the website and similarly you should be able to scrape the WebTorrent<>BitTorrent tracker's website/API.

But realistically: no, I don't think you can enumerate that: Really though, someone who knows what they are talking about should chip in.

**Comment by DiegoRBaquero** [comment]
For the moment there's no way to list all currently available torrent on the webrtc network. Room for a project there!

**Comment by feross** [comment]
Please don't discuss third-party torrent tracker sites that encourage copyright infringement on this issue tracker. We cannot help with such requests. Do not use WebTorrent for piracy.
