### ISSUE TITLE
File path seeding problems

### ISSUE THREAD

**Issue by shime** [feross/webtorrent#495]
I'm trying this one 

```
var client = new WebTorrent()
client.seed('foo')
```

And getting back 
```
Uncaught TypeError: fs.stat is not a function
```

Documentation clearly says that the seed method accepts file path as a string. What am I doing wrong?

[JS Bin example](http://jsbin.com/baqasixuje/edit?html,output)

**Comment by shime** [comment]
I've overriden the method that was throwing that exception and got to
```
Uncaught Error: filesystem paths do not work in the browser
```
So it's currently not possible to seed anything that's outside `input[file]`?

**Comment by elad** [comment]
Right, probably by (browser) design. Otherwise it would mean Javascript code could seed arbitrary files from your computer! :) I think at least Chrome's sandbox stops this type of access and requires explicit user intervention (the file input) to do it.

In other words, this isn't a bug and it's outside the scope of WebTorrent, IMO.

**Comment by ericwooley** [comment]
It might be a bug in chrome, or the documentation could be referring to when you are using webtorrent-hybrid, which allows you to read from the file system.

**Comment by elad** [comment]
The API documentation isn't clear, but the examples before it distinguish between "in the browser" and "in node.js." In the browser you must have user intervention (drag and drop, for example). In node.js, you don't.

As for Chrome, it's definitely not a bug. Even the dead/deprecated/abandoned HTML5 file system API would only let you access files inside the sandbox rather than arbitrary files on the machine.

**Comment by feross** [comment]
Filesystem access is not allowed in the browser. Using a file path is only supported when using WebTorrent in node.js.

We should improve the error message that you get since `Uncaught TypeError: fs.stat is not a function` isn't helpful.

**Comment by feross** [comment]
The error message is fixed in `create-torrent` with these commits:

https://github.com/feross/create-torrent/commit/2d4f01eb318d09105c988af974b5e25340f615c5
https://github.com/feross/create-torrent/commit/1dc59e7d044a4428d01269a171357a5b486072b1
