### ISSUE TITLE
Not following BEP12 'announce-list'

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/webtorrent#513]
At the moment WebTorrent announces to all the announce-list instead of following the specification.

Right now, as default trackers are default listed, a torrent should only use BTorrent's tracker (2nd default) if it can't reach WebTorrent's tracker. It, howevers, uses both trackers.

http://bittorrent.org/beps/bep_0012.html

**Comment by feross** [comment]
Thanks for looking into this.

I think the spec is a bit vague here, to be honest. I read it this way: Announce to all tiers, but in order. Example: Announce to Tier 1, wait for response or timeout, then announce to Tier 2, etc. If there is more than one tracker in a tier, then any tracker will do and one-at-a-time should be tried as a load-balancing strategy.

WebTorrent currently just announces to every tracker immediately.

Notably, Transmission appears to announce to all tiers at the same time, but I haven't checked how it handles multiple trackers in the same tier.

Announcing to all tiers at the same time seems perfectly okay. It doesn't materially change what would happen since all tiers will be announced to anyway. It just improves the speed of peer finding. I'm fine with copying Transmission's behavior here.

As far as multiple trackers in a single tier – I've never seen a torrent like this, so I don't think it's super important to get this right. @DiegoRBaquero - Is this actually an issue for you? If not, I'd prefer to keep the implementation simple.

Note: `create-torrent` always produces an `announce-list` with each tracker in its own tier. I used to allow the user to control the tiers but never found it useful, so I removed the feature. Since `tracker.webtorrent.io` and `tracker.btorrent.xyz` are in different tiers, they should both be announced to (by my reading of the spec).

**Comment by feross** [comment]
Sorry – was wrong. You can still specify the full `announce-list` with `create-torrent`. Updated comment above.

**Comment by DiegoRBaquero** [comment]
It's doesn't really bother me not following the specification. I just had a look into it because of my comment #427 where I suggest that using opts.announceList overrides the default trackers list and using opts.announce adds your specified trackers to the default ones.

`create-torrent` opts.announce and opts.announceList do the same thing right now: override the default trackers and set the announceList the the specified tracker(s).

I see an opportunity there to add the extra functionality.

In my opinion, announcing to all available trackers in all available tiers immediately should remain and be the default.

**Comment by feross** [comment]
Nice, closing this now.
