### ISSUE TITLE
Ability to update torrent content

### ISSUE THREAD

**Issue by sunk818** [feross/webtorrent#556]
Not sure how others are using WebTorrent. I'm curious about the ability to create a web site and publish updates to the web site. ZeroNet does this well for small web sites, but not for web sites that hundreds of megabytes of HTML.

I noticed Bittorrent has an enhancement draft for update URLs in Bittorrent: http://www.bittorrent.org/beps/bep_0039.html

Curious if WebTorrent is useful for publishing and updating large amounts of HTML.

**Comment by DiegoRBaquero** [comment]
You would need a central server to provide the updated/latest torrent.

I've been looking a lot into this kind of things. On way is to reference the location of where I can find the located version inside the torrent. Another way, and I'd prefer because it can be built in top for WebTorrent for the browsers is that you, in your website download the latest .torrent and then render it.

Something like `publish` packs the html, css & js into a .torrent called latest.torrent and pushes it to yourdomain.com/latest.torrent . Then, users would go in your website and the client uses latest.torrent and then renders it. 

In BTorrent, I'm making a browser that will support the exact features I propose. The "URLs" would be the infohashes/magnets/.torrent . Instead of linking with href you'd link with wtref.

**Comment by sunk818** [comment]
Could the update url be via dht that points to a new magnet link (the new torrent)? No central server required?

For webtorrent videos, it seems videos are streamed so the file pieces have to be served sequentially for optimal viewing of video.

So instead of href, wtref is a replacement and the browser accesses different resources as needed on demand? Or would the entire torrent need to complete first before serving updated content?

**Comment by devTristan** [comment]
This can be accomplished by an extension to the bittorrent protocol. You can seed a public key file and distribute verifiable updates across the network by sending signed messages to any peers you can find, and rebroadcasting valid signed messages that you receive.

**Comment by feross** [comment]
This is probably best accomplished outside of WebTorrent right now, with something like BEP44. This lets you set, get, and update key/values on BitTorrent DHT nodes. So this will let you update a "pointer" to point at the latest torrent. And you can implement a kind of linked list structure where each new torrent points to the last.

```
get(key) ---> info hash 1 ---> info hash 2
                           |                         |
                           v                        v
                      content 1           content 2
```

The [`bittorrent-dht`](https://github.com/feross/bittorrent-dht) package already supports BEP44.

(It won't work in the browser because there's no WebRTC DHT yet.)

**Comment by feross** [comment]
Feel free to continue discussing this topic here, but I'm going to close this since it's not an issue with WebTorrent. :)
