### ISSUE TITLE
Only show used candidates on https://webtorrent.io/

### ISSUE THREAD

**Issue by KaptenJansson** [feross/webtorrent#578]
Currently https://webtorrent.io/ shows local host candidates with private IP addresses which I will never be able to access which indicates it displays the "first" (or some other type of selection) candidates seen.

Instead it should show reachable candidates that are actually used instead.

**Comment by DiegoRBaquero** [comment]
The private IPs are actually connected wires which transfer data to you. If not private, they are peers using public IPs.

**Comment by KaptenJansson** [comment]
Well ofc they are sending data, however it does not make sense showing host candidates that I can never connect to directly thus the demo is not correctly conveying which endpoint I have established a peerconnection to.

**Comment by DiegoRBaquero** [comment]
Those are not candidates, else there would be more than 30 instantly. The shown peers are connected peers, not candidates.

**Comment by KaptenJansson** [comment]
Right, what I meant is that I cannot possibly connect to private IP's from my network (unless they are on my network) hence it looks like there something wrong with demo. As you mentioned, they are connected peers hence it makes sense displaying the IP address that I'm actually connected to. 

It looks like you are using "any" candidate as a peer identifier in the demo rather than the actual connected IP address.

Does that make sense?

**Comment by feross** [comment]
@KaptenJansson Thanks for opening this issue. You are correct. Sometimes local IP address candidates are mistakenly shown on https://webtorrent.io. This is a bug in [`simple-peer`](https://github.com/feross/simple-peer).

I was able to fix this bug in Chrome, but it still exists in Firefox, as you can see here: https://github.com/feross/simple-peer/issues/63

If you're interested, please contribute a fix!

(I'm going to close this issue here, since it's already being tracked on the `simple-peer` repo.)

**Comment by feross** [comment]
This is fixed now! Released in `simple-peer` 5.12.0.

**Comment by KaptenJansson** [comment]
Good stuff ;) When will it be pushed to webtorrent.io?

**Comment by feross** [comment]
It's published to webtorrent.io now.

**Comment by KaptenJansson** [comment]
Just tested it and now I just see public-ally accessible IP addresses, awesome!

**Comment by feross** [comment]
@KaptenJansson thanks!
