### ISSUE TITLE
private torrent not download

### ISSUE THREAD

**Issue by lamo2k123** [feross/webtorrent#613]
my code: http://codepen.io/anon/pen/GoPLVM/?editors=0010

torrent file if key private 1

**Comment by devTristan** [comment]
Since what you're trying to do is illegal, your issue will most likely be closed, as is the [policy of this project](https://github.com/feross/webtorrent/blob/master/CONTRIBUTING.md). Webtorrent requires other webtorrent-compatible peers to be in the swarm, discoverable via a webtorrent-compatible tracker.

**Comment by feross** [comment]
Please do not use WebTorrent for copyright infringement. We cannot help you.
