### ISSUE TITLE
Html5 webtorrent music player using aplayer

### ISSUE THREAD

**Issue by enorrmann** [feross/webtorrent#651]
I would like to introduce my beta app, it is called youshark ;)
html5 based webtorrent player, using aplayer 

http://youshark.neocities.org/

https://github.com/enorrmann/youshark

**Comment by feross** [comment]
Thanks for sharing your project, best of luck to you!! :smile:

**Comment by feross** [comment]
Any chance you're going to make the initial UI that the user sees better? Could make this a lot cooler.

**Comment by enorrmann** [comment]
of course !  for me is logic first, then UI, I will continue to work on this, just wanted to share asap

**Comment by enorrmann** [comment]
updated :+1:

**Comment by feross** [comment]
@enorrmann Wow, that looks really nice! Have you considered contributing to [WebTorrent.app](https://github.com/feross/webtorrent-app)?

FYI, the WebTorrent script changed to no longer add tracker servers by default. So, you might want to change the box at the top to say "Paste magnet URI here" instead of "Paste hash here" and stop appending `magnet:?xt=urn:btih:` to the front of the input.

**Comment by feross** [comment]
More context about the decision to stop automatically adding trackers here: https://github.com/feross/webtorrent/issues/672#issuecomment-196614860
