### ISSUE TITLE
WebTorrent not support for Buffer on browser

### ISSUE THREAD

**Issue by jimliang** [feross/webtorrent#671]
* WebTorrent version: 0.85.1
* Node.js version: v4.2.2
* Browser name/version (if using WebTorrent in the browser): Chrome/49.0.2623.87

using webpack as a bundler.
Because it do not support `require('webtorrent')` with webpack(see https://github.com/feross/webtorrent/issues/347 ),i use `require('webtorrent/webtorrent.min')` in the browser.
But it return undefined when `webtorrent.get(new Buffer(...))`.
It seen  that **webtorrent.min** cannot parse a Buffer Object.

**Comment by Autarc** [comment]
The problem is that `create-torrent` currently expects buffers and streams to have a name. While its not common you can just attach the `name` property to the buffer object. Perhaps in an [upcoming version](https://github.com/feross/create-torrent/pull/31) this will be obsolete.

Aside of using the static **webtorrent.min** built you can checkout [the configurations](https://github.com/Autarc/webtorrent/tree/improve-integration-instructions#webpack) which have to be set to enable the `webtorrent` package to work in webpack.

**Comment by feross** [comment]
@Autarc The `create-torrent` issue seems unrelated. @jimliang is discussing the `client.get` function, which is used to look up an existing torrent.

@jimliang Please share a complete code example. It sounds like you're using the wrong function. `client.add` allows you to download a new torrent, not `client.get`.

**Comment by jimliang** [comment]
html:

    <script src="webtorrent.min.js"></script>
    <script src="bundle.js"></script>

bundle.js is created by webpack.Source:


    const client = new WebTorrent();
    client.add(new Buffer(...),(torrent)=>{});

Throwing `Invalid torrent identifier(…)` on the browser.

Now I use  **browserify** instead of webpack.This issue can close. :3

**Comment by Yhozen** [comment]
@Autarc I would like to see those configurations but the link is dead
