### ISSUE TITLE
Add websocket trackers directly in webtorrent

### ISSUE THREAD

**Issue by rom1504** [feross/webtorrent#672]
websocket trackers are added to existing torrents in all the webtorrent dependencies that support webrtc:
* [webtorrent-hybrid](https://github.com/feross/webtorrent-hybrid/blob/d920fa1e01a6ecaabbcbf040d666740bf74569b4/lib/global.js#L6)
* [instant.io](https://github.com/feross/instant.io/blob/c8924fe4cea665c938911edf5b7efaa2c4b1e9ab/client/index.js#L15)
* [webtorrent-app](https://github.com/feross/webtorrent-app/blob/6ba0d65daf8d767d500faf8829650839df6b2339/renderer/index.js#L34)

It would probably make sense to put that directly in webtorrent, if there is webrtc support.

Also see that discussion https://github.com/feross/webtorrent-hybrid/pull/22#discussion_r55977228

**Comment by rom1504** [comment]
That global is handled in [torrent.js](https://github.com/feross/webtorrent/blob/52452e4bd91513d82f85c774b58c3a9ba5cfd22b/lib/torrent.js#L253)

**Comment by DiegoRBaquero** [comment]
WebRTC Support is also available on the client. No need to require simple-peer :)

**Comment by rom1504** [comment]
@DiegoRBaquero what do you mean by "the client" exactly ? Is .WEBRTC_SUPPORT available anywhere else ?

**Comment by DiegoRBaquero** [comment]
@rom1504 https://github.com/feross/webtorrent/blob/master/index.js#L21

**Comment by rom1504** [comment]
Yes but I can't require the index.js from torrent.js, see #673

**Comment by DiegoRBaquero** [comment]
You don't need to require it, a Torrent has the reference to the client. You can move the code to the constructor.

**Comment by rom1504** [comment]
Well it's all global anyway, I could put it anywhere. But I think it belongs to torrent.js since that's where it's used.

**Comment by DiegoRBaquero** [comment]
But, and anyone correct me if I'm wrong, wouldn't it be better inside the constructor after this line? [torrent.js#L76](https://github.com/rom1504/webtorrent/blob/add_default_webrtc_trackers/lib/torrent.js#L76)

**Comment by feross** [comment]
> It would probably make sense to put that directly in webtorrent, if there is webrtc support.

It's actually not a very good idea to make the webtorrent library automatically connect to third party servers without user consent. Because automatically adding servers to .torrent files is basically doing that. I actually made a change very recently to *remove* the behavior of adding trackers by default to added torrents here: https://github.com/feross/webtorrent/commit/bc69413a78d7bb56f3ee63f29e77694fa3cc86e9

Instant.io is a file sending service, so it's fine for it to add it's own and other trackers by default.

WebTorrent.app and webtorrent-hybrid should probably stop adding trackers to added files as well (`client.add`). When the user wants to seed files (`client.seed`), on the other hand, I think it's fine to use some reasonable defaults *when the user doesn't specify their own trackers*.

Going forward, it's safest to ensure that magnet links or .torrent files explicitly contain the trackers to be used. `client.seed` and `create-torrent` will continue to do the right thing, so this shouldn't be very hard.

**Comment by rom1504** [comment]
I agree.
However we got to keep in mind that means if you download a (not created with webtorrent) torrent with webtorrent-app, it won't be made available to instant.io.
