### ISSUE TITLE
External players like VLC

### ISSUE THREAD

**Issue by diimdeep** [feross/webtorrent#728]
Until media playback will be feature rich, with subtitles, audio track selection etc., might be good to support external players. 
Although manual open file in VLC works just fine.
Might help https://github.com/mafintosh/peerflix/blob/master/app.js#L28

**Comment by rom1504** [comment]
it is already possible in https://github.com/feross/webtorrent-cli

Maybe you meant to open an issue in https://github.com/feross/webtorrent-desktop/issues

@feross looks like there is some confusion between webtorrent and webtorrent-desktop. Might be caused by webtorrent-desktop about only telling about webtorrent and not webtorrent-desktop

**Comment by diimdeep** [comment]
Wrong repo, my fail. Recreated https://github.com/feross/webtorrent-desktop/issues/368

**Comment by feross** [comment]
@rom1504 I think the confusion might be due to the big green GitHub button on https://webtorrent.io/desktop. Will make it point to `webtorrent-desktop` when on the Desktop page.

**Comment by feross** [comment]
@rom1504  Fixed now.
