### ISSUE TITLE
not automatically delete?

### ISSUE THREAD

**Issue by Alexaalex93** [feross/webtorrent#748]
* WebTorrent version: 0.3.3
I've been watching some movies on it and that movies dont delete automatically they keep in downloads. I think that they should remove automatically, right?

**Comment by DiegoRBaquero** [comment]
This is an issue for the desktop version, however I'm going to answer here. WebTorrent is a torrents-first streaming client, so like any other torrent client, the torrent will remaing after they have been downloaded. Streaming is just an extra feature it has.

**Comment by Draxler** [comment]
@DiegoRBaquero 

But Webtorrent client do have another issue (simmilar to what main tile is saying). 
After torrent (movie) is downloaded with Webtorrent client (desktop Win 7) and user delete that same torrent from Webtorrent client, Client removes file only from Webtorrent client, but NOT from PC it self. User need to go to PC directory where that downloaded file is stored and then delete that same file again (which user already deleted that same file from Webtorrent client). Files were not completley removed from PC when downloaded with Webtorrent client and if user try to delete that file with Webtorrent client. It only remove file from client (Webtorrent) but file it self was not deleted from directory where file was downloaded. (I'm sorry if i maybe overlooked and this issue was already menched someplace else, i didn't see it. ) 
Regards

**Comment by feross** [comment]
Yep, @DiegoRBaquero is correct.
