### ISSUE TITLE
Webtorrent using unnecessarilly using too much cpu

### ISSUE THREAD

**Issue by rjdp** [feross/webtorrent#766]
* WebTorrent version:0.3.3
* Node.js version:5.0.0
* Browser name/version (if using WebTorrent in the browser):
![screenshot from 2016-04-24 00-23-00](https://cloud.githubusercontent.com/assets/7734938/14763434/2d81d77a-09b3-11e6-888f-7780b5685019.png)

**Comment by feross** [comment]
@rjdp This is a known issue with the desktop app that will be fixed in around 7 weeks. See https://github.com/feross/webtorrent-desktop/issues/353 for more information.

**Comment by rjdp** [comment]
tnx.

**Comment by feross** [comment]
Sure thing.

**Comment by feross** [comment]
FYI: 

As a stopgap solution for OS X only, we are going to disable WebRTC peers in the next version of WebTorrent (v0.4.0) since the 100% CPU issue is makes the app look broken, when it's not even our fault.

Once Chrome 51 is included in Electron, we'll undo this change and re-enable WebRTC peers on OS X.

PR here: #511
