### ISSUE TITLE
Does chromecast playback work?

### ISSUE THREAD

**Issue by rclai** [feross/webtorrent#786]
```
$ webtorrent --version
1.1.3 (webtorrent 0.91.2)
```

Hi, this project is great. Torrents download very quickly.

I did:

```
chromecast [magnet url] --chromecast
```

but my Chromecast doesn't seem to play it but download does work. Do I need to anything else to make it work? Does it have anything to do with the fact that my Chromecast has a different name?

**Comment by rom1504** [comment]
Are you talking about https://github.com/feross/webtorrent-cli/blob/master/bin/cmd.js#L190 ?

**Comment by feross** [comment]
@rclai Yes, Chromecast playback does work. One thing that might be happening is that you have multiple Chromecasts on your network and a random one is being chosen.

There's currently no way to choose which Chromecast you want to cast to. What happens when you use [WebTorrent Desktop](https://webtorrent.io/desktop)?

**Comment by rclai** [comment]
I'll give that a try.
