### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by jsinchrist** [feross/webtorrent#822]
I'm just trying to uninstall on Windows 10, and cannot find the Uninstall option anywhere.   The application would be awesome if it worked with all technologies.  I believe I will try again when it is.  For now though, how do I uninstall this?
* WebTorrent version:
* Node.js version:
* Browser name/version (if using WebTorrent in the browser):

**Comment by feross** [comment]
Sorry you want to uninstall WebTorrent Desktop.

You should be able to find an uninstaller for WebTorrent Desktop in "Programs & Features" or "Apps & Features" in the Windows Control Panel. For example:

<img width="853" alt="screen shot 2016-06-05 at 18 44 38" src="https://cloud.githubusercontent.com/assets/121766/15809863/a872d446-2b4d-11e6-884f-2e246cbdacf1.png">

If you don't see that it could be because you installed `webtorrent-desktop` from npm. You can remove it by running `npm uninstall -g webtorrent-desktop` from the Node.js command line.
