### ISSUE TITLE
torrent.files[i].done is always false, even if file is fully downloaded

### ISSUE THREAD

**Issue by romaincointepas** [feross/webtorrent#829]
* WebTorrent version: 0.94.3
* Node.js version: 6.1.0
* Electron version: 1.2.1

However, if I `console.log(torrent.files[i])`, I see `done: true`.

Any idea?

**Comment by feross** [comment]
Sounds like it's probably a bug in your code. Are you checking the value of `torrent.files[i]` done before the file is actually done?

**Comment by romaincointepas** [comment]
The file is done for sure.

I'm checking for file.done in the client.add callback (reopen the app with a torrent/file that has been downloaded in a previous session).

I'm also in an Electron renderer, if that matters.

Here is a quick test code:

``` coffee
client.add magnetURL, (torrent) ->
    file = torrent.files[0]
    console.log 'PRE-TEST'
    console.log file.done
    console.log file
    console.log file.done
    console.log 'POST-TEST'
```

And here is what I get in the Console:

<img width="775" alt="screen shot 2016-06-08 at 2 09 25 pm" src="https://cloud.githubusercontent.com/assets/797899/15884399/b7387986-2d82-11e6-812f-d139cf9483b6.png">

**Comment by feross** [comment]
The file won't be done immediately when the onTorrent callback is called. You can listen for the `'done'` event to find out when the file is done:

```js
client.add(magnet, function (torrent) {
  var file = torrent.files[0]
  file.on('done', function () {
    file.done // true
  })
})
```

You're seeing that it's true when you expand the object in the inspector because the developer tools just save a reference to the object and don't resolve the values of it's properties until you expand the object.

If you hover over the 'i' icon in the interface you'll see:
