### ISSUE TITLE
Stream video in browsers that don't support MediaSource

### ISSUE THREAD

**Issue by jakefb** [feross/webtorrent#830]
I have noticed some browsers that don't support MediaSource or WebRTC (Safari on iOS) are still able to download a video torrent from a HTTP web seed, but cannot append the buffer with the MediaSource API.

It would be great to get torrents streaming on iOS. What are some possible ways around this?

**Comment by yciabaud** [comment]
In my experience, the only way to go smoothly if there is no MediaSource API available is to create a video elem with the webseed url.

Another solution would be to make a video element with the blob URL but I guess you will have to wait for the download and it will not work in iOS with the external video player...

**Comment by feross** [comment]
Safari actually supports MediaSource, but the `videostream` package lost support for it in version 2.0.0. It got a LOT better in other ways and it's WAY more reliable, so we can't just downgrade to 1.x in order to get support back. Issue here: https://github.com/jhiesey/videostream/issues/24

I think @yciabaud's workaround sounds good, but if you detect MediaSource support, you'll need to special-case new Safari for now, since it supports MediaSource but `videostream` doesn't yet.
