### ISSUE TITLE
add file and create the hash code problem

### ISSUE THREAD

**Issue by yanshekki** [feross/webtorrent#841]
* WebTorrent version: https://www.extratown.com/plugins/webtorrent-master/webtorrent.min.js
* Node.js version: 
* Browser name/version (if using WebTorrent in the browser): chrome and firefox

this is my web page for test and develop webtorrent programme:
https://www.extratown.com/webtorrent

the problem that when i add the file over than 100mb in the browser will crash, if i use the android chrome browser over than 15mb will crash. and the cpu loading 120%-180%.

off topic:
1, the trackers server in list about 1 websocket 5% cpu is it normal?

2, i trying to use webtorrent to develop video streaming. but now maybe have no browser good for recording and play video. have people interested together develop?
the test link: https://www.extratown.com/streaming
(just chrome can recording and only firefox can play streaming)

my english not good, please forgive me, thank you!

**Comment by feross** [comment]
@yanshekki Not sure why you're having issues. What OS and browser are you using on desktop? I just tested uploading a 200MB video file on that URL without issues.

What happens when you use https://instant.io? I can get a 1GB to work there, easily.

Maybe you have a browser extension that's doing something really inefficient with the webpage? Try it in a incognito/private window with no extensions enabled.

If you have further information to share, please comment and we'll re-open this issue.
