### ISSUE TITLE
Can it be used in a private local area network ? 

### ISSUE THREAD

**Issue by amarcul** [feross/webtorrent#858]
Can It be used in local area personal network that has no internet access , just used to share data ?

**Comment by astro** [comment]
Please have a look at [Zeroconf Peer Advertising and Discovery](http://bittorrent.org/beps/bep_0026.html) and also [Local Service Discovery](http://bittorrent.org/beps/bep_0014.html). [Private Torrents](http://bittorrent.org/beps/bep_0027.html) should also be of interest in order to avoid leaking data while connected to the Internet.

**Comment by feross** [comment]
Yes, you can use WebTorrent on a private network. But, you'll want to ensure that you do one of the following:

## 1. Run a local tracker server for finding peers

- Run your own tracker instance with [bittorrent-tracker](https://github.com/feross/bittorrent-tracker)
- When starting up the tracker, you can decide to enable each type of tracker: UDP, HTTP, WS. I recommend enabling them all.
- Pass in the URL of your tracker via the `{ announce: [ 'http://host:port', 'udp://host:port', 'ws://host:port' ] }` option to `client.add()`

## 2. Rely on a local-only DHT for finding peers.
- Run your own DHT bootstrap server instance with [bittorrent-dht](https://github.com/feross/bittorrent-dht)
- Pass in the URL of your DHT bootstrap server via the `{ dht: { bootstrap: 'host:port' } }` option to the `WebTorrent` constructor

## 3. Tracker + DHT

- Do both (1) and (2) together.
