### ISSUE TITLE
Choking peers loop

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/webtorrent#890]
- WebTorrent version: latest (0.96.4)
- Browser name/version (if using WebTorrent in the browser): Chrome 52

![Log](https://www.dropbox.com/s/kp5esnjijibgxlv/Screenshot%202016-08-26%2015.36.07.png?dl=1)

Choking peers like this should be removed.

**Comment by feross** [comment]
I've seen this happen before as well.

The "peer is choking" message comes from `bittorrent-protocol` and it can happen for two reasons:

1. We have a outstanding pieces requests to a peer, and the peer decides to choke us. So the requests all get canceled.

1. We are trying to make a request to a peer that is choking us. This is not allowed and would cause the peer to disconnect from us for misbehaving, so it is prevented by `bittorrent-protocol` library.

I think we're probably seeing the second case here, since it's the same piece and offset that are being repeatedly requested. So this is likely a bug in `webtorrent` itself.

**Comment by gpetrov** [comment]
@feross  yes we also observed choking hangs, see https://github.com/feross/webtorrent/issues/963
it will be nice if this get solved or a better choke handling gets implemented so the download don't just hangs

**Comment by gpetrov** [comment]
web seeds shouldn't choke, added PR https://github.com/feross/webtorrent/pull/972

**Comment by feross** [comment]
Fixed by #972
