### ISSUE TITLE
How to make screenshots?

### ISSUE THREAD

**Issue by iLeonidze** [feross/webtorrent#893]
I want my app automatically capture over 10-20 random screenshots from the mp4 video in the torrent, without downloading it, but I can't find this feauture in the API.

**Comment by DiegoRBaquero** [comment]
Without downloading it? It's impossible. You can select the 10-20 random parts to screenshots selecting 10-20 random pieces, but those will definitely be downloaded.

This feature is not part of a torrent client function, must be built on top of it. Would be great that if you find it or build it, that you shared it with us :)

**Comment by iLeonidze** [comment]
@DiegoRBaquero I incorrectly explained my idea - yes, I have to download this pieces, but I don't want to download full videofile. For example, in WebTorrent, when we start downaloding some video, we can see preview in main menu. So by this way I want to get "screenshots".

**Comment by feross** [comment]
@iLeonidze You can see the code for how we do this in WebTorrenT Desktop here: https://github.com/feross/webtorrent-desktop/blob/64f49e4d4fa742d18809e54be3edd93d65055c39/src/renderer/lib/torrent-poster.js

We take advantage of the fact that we're running in a browser context (since it's an Electron app) to implement it simply. Basically, we add the video file to a `<video>` tag, then we seek to the part we want to screenshot and pull out the pixel data using a canvas. You can see that part here: https://github.com/feross/webtorrent-desktop/blob/64f49e4d4fa742d18809e54be3edd93d65055c39/src/renderer/lib/capture-video-frame.js

I plan to pull these out into their own npm packages so you can use them more easily.

**Comment by feross** [comment]
Here's one of them: `capture-frame` https://github.com/feross/capture-frame
