### ISSUE TITLE
ws:// seeding in nodejs support? 

### ISSUE THREAD

**Issue by abans** [feross/webtorrent#896]
* WebTorrent version:0.96
* Node.js version:6.3.0
* Browser name/version (if using WebTorrent in the browser):Chrome 53

Can you please add websocket protocol supported in nodejs?
I hope seeding in nodejs, and use the browser to download.

**Comment by DiegoRBaquero** [comment]
I've been thinking of implementing this myself, would definitely be superior than webseeding.

**Comment by feross** [comment]
@abans You can use [`webtorrent-hybrid`](https://www.npmjs.com/package/webtorrent-hybrid) if you want to have WebTorrent in Node.js connect to WebRTC peers.

@DiegoRBaquero You must be discussing something different. Can you clarify?

**Comment by DiegoRBaquero** [comment]
@feross I think this is about client-server seeding, but instead of http(s) use ws(s) for seeding.

**Comment by feross** [comment]
@DiegoRBaquero Hey, this seems like a potentially cool idea. What do you think about writing up a spec for what this would look like and trying to get it approved as a BEP, then we can implement it. 

Without a BEP, I don't think we should include it. Also, you might want to test a bit more first since web seeds are already really light weight IMO. They are just http requests, which are really efficient in node.js and the browser. With HTTP2, the HTTP requests become a lot more efficient like WebSockets (re-using the same connection). So, I'm not sure there's a need for this feature.

Once we improve our web seed implementation, performance should improve even more: https://github.com/feross/webtorrent/issues/650

**Comment by feross** [comment]
Closing for now.

**Comment by DiegoRBaquero** [comment]
@feross I investigated many ways to do this and the most efficient would require building a bittorrent-protocol compatible websocket wire. Just for the sake of having it, it is not worth it. HTTP2 can perform the job with the same, if not better, performance with the added security restriction of TLS. After many hours of trying to build a prototype I came to the conclusion that I wouldn't build it and nobody should, is a waste of dev time, plus the added documentation that it would require.

Webseeding is pretty established and we should focus on improving it instead of dedicating any work towards websocket seeding.

@abans If you need any help implementing HTTP2 I would kindly help you.
