### ISSUE TITLE
info required

### ISSUE THREAD

**Issue by rafaelleru** [feross/webtorrent#955]
where I can find information about play a stream created by:

stream = file.createReadStream([opts])

I want to play this stream directly into my player, to download files faster.

**Comment by feross** [comment]
`file.createReadStream()` returns a node.js Readable stream. Documentation available here: https://nodejs.org/api/stream.html#stream_readable_streams

This returns the raw video data. It's not going to be easy to pipe that straight into a video player. That's why we created the `file.renderTo()` and `file.appendTo()` methods. There's a lot of work required to process the video file into a format that can be streamed into the video tag (using the `MediaSource` API, which has very strict requirements about the packaging of the video).

Handling seeking is also a difficult challenge – you have to translate the time that the user seeked to (in seconds) into a byte offset into the file. This requires parsing the MP4 metadata to understand the file structure.

All this magic is currently handed in the [`render-media`](https://www.npmjs.com/package/render-media) and [`videostream`](https://www.npmjs.com/package/videostream) packages.
